### ISSUE TITLE
AttributeError: 'list' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by bingjie3216** [lvwerra/trl#286]
To reproduce:
after accelerate config: 8 V100 GPUs

run: accelerate launch gpt2-sentiment.py

Error:
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/jbing-gpu4/code/Users/jbing/code/trl/examples/sentiment/scripts/gpt2-sentiment.py", line 176, in <module>
                response_tensors = ppo_trainer.generate(    response_tensors = ppo_trainer.generate(response_tensors = ppo_trainer.generate(response_tensors = ppo_trainer.generate(
response_tensors = ppo_trainer.generate(

  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
        input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs        input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
    input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargsinput_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargsAttributeError

AttributeError
: : AttributeError'list' object has no attribute 'unsqueeze'AttributeError'list' object has no attribute 'unsqueeze'AttributeError: : : 'list' object has no attribute 'unsqueeze''list' object has no attribute 'unsqueeze''list' object has no attribute 'unsqueeze'

    response_tensors = ppo_trainer.generate(
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
    input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
AttributeError: 'list' object has no attribute 'unsqueeze'
    response_tensors = ppo_trainer.generate(
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
    input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
AttributeError: 'list' object has no attribute 'unsqueeze'
    response_tensors = ppo_trainer.generate(
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 375, in generate
    input_ids=query_tensor.unsqueeze(dim=0), **generation_kwargs
AttributeError: 'list' object has no attribute 'unsqueeze'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31368) of binary: /anaconda/envs/rlhf/bin/python
Traceback (most recent call last):
  File "/anaconda/envs/rlhf/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 914, in launch_command
    multi_gpu_launcher(args)
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in multi_gpu_launcher
    distrib_run.run(args)
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/envs/rlhf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by bingjie3216** [comment]
Actually the solution is to install the latest version from source instead of pip install trl

Solution:
pip install -e .

**Comment by younesbelkada** [comment]
Awesome that it worked! Feel free to close the issue
