### ISSUE TITLE
StackLLaMA - ValueError: Please specify `target_modules` in `peft_config`

### ISSUE THREAD

**Issue by thinh-huynh-re** [lvwerra/trl#307]
Hi, thank you for your amazing work.
After reading [StackLLaMA: A hands-on guide to train LLaMA with RLHF](https://huggingface.co/blog/stackllama), I try to run StackLLaMA first phase.
When I run `supervised_finetuning.py` with the model `aleksickx/llama-7b-hf`, I encounter the following error:

```
ValueError: Please specify `target_modules` in `peft_config`
```

Here is the full logs:

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/re/trl/examples/stack_llama/scripts/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/re/trl/examples/stack_llama/scripts/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /home/ocr/miniconda3 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/re/trl/examples/stack_llama/scripts/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
Setting EOS, BOS, and UNK tokens for LLama tokenizer
Loading the dataset in streaming mode
100%|█████████████████████████████████████████████████████████████████| 400/400 [00:13<00:00, 30.06it/s]
The character to token ratio of the dataset is: 3.19
Loading the model
Loading checkpoint shards: 100%|████████████████████████████████████████| 33/33 [00:23<00:00,  1.38it/s]
Traceback (most recent call last):
  File "/home/re/trl/examples/stack_llama/scripts/supervised_finetuning.py", line 346, in <module>
    main(args)
  File "/home/re/trl/examples/stack_llama/scripts/supervised_finetuning.py", line 334, in main
    run_training(args, train_dataset, eval_dataset)
  File "/home/re/trl/examples/stack_llama/scripts/supervised_finetuning.py", line 269, in run_training
    model = get_peft_model(model, lora_config)
  File "/home/re/trl/examples/stack_llama/scripts/env/lib/python3.10/site-packages/peft/mapping.py", line 142, in get_peft_model
    peft_config = _prepare_lora_config(peft_config, model_config)
  File "/home/re/trl/examples/stack_llama/scripts/env/lib/python3.10/site-packages/peft/mapping.py", line 117, in _prepare_lora_config
    raise ValueError("Please specify `target_modules` in `peft_config`")
ValueError: Please specify `target_modules` in `peft_config`
```

Script to reproduce
```
python supervised_finetuning.py --model_path=aleksickx/llama-7b-hf \
        --streaming --no_gradient_checkpointing --learning_rate 1e-5 \ 
        --max_steps 1000 --output_dir ./llama-se
```

My environments: `python3.10`
```
peft==0.2.0
torch==2.0.0
transformers==4.28.1
datasets==2.11.0
sentencepiece==0.1.98
protobuf==3.20.3
accelerate==0.18.0
bitsandbytes==0.38.1
```

Questions:
1. Is the model `aleksickx/llama-7b-hf` not compatible to StackLLaMA?

2. What do I need to define  `target_modules` in  `LoraConfig` here ?
https://github.com/lvwerra/trl/blob/160d0c9d6cdbc8b247bad4aa8f97f2c57dc4a60f/examples/stack_llama/scripts/supervised_finetuning.py#L202-L208

**Comment by younesbelkada** [comment]
Hi @thinh-huynh-re 
Thank you for your interest in this work
Llama support has been added very recently into `peft`. Hence you need to update your `peft` library to run that script:

```bash
pip install git+https://github.com/huggingface/peft
```

However, you can directly use that version and just specify `target_modules` as stated on the issue. That argument is used to specify the name of the module you want to replace with the LoRA module. In the Llama case, I'd expect to replace the [query and key layers](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L176-L177) to LoRA modules therefore:

```python
lora_config = LoraConfig( 
     r=16, 
     lora_alpha=32, 
     lora_dropout=0.05, 
     bias="none", 
     task_type="CAUSAL_LM", 
     target_modules=["q_proj", "k_proj"],
 ) 
```
should do the trick!

**Comment by thinh-huynh-re** [comment]
It works. 
Thank you for your quickly support!
