### ISSUE TITLE
ValueError: can only convert an array of size 1 to a Python scalar

### ISSUE THREAD

**Issue by vpegasus** [lvwerra/trl#329]
I reproduce `rl_training.py` with the following modification (by following #325 ) :
```
tokenizer =LlamaTokenizer.from_pretrained("hf-internal-testing/llama-tokenizer")
```

@younesbelkada  please give me a hand, thanks.

```bash
CUDA_VISIBLE_DEVICES= accelerate launch rl_training.py \
> --log_with=wandb --model_name=/xxx/merged7bsft \
> --reward_model_name=/xxx/merged7breward \
> --adafactor=False \
> --tokenizer_name huggingface/llama-7b \
> --save_freq=100 \
> --output_max_length=128 --batch_size=4 --gradient_accumulation_steps=8 \
> --batched_gen=True --ppo_epochs=4 --seed=0 --learning_rate=1.4e-5 \
> --early_stopping=True --output_dir=llama-se-rl-finetune-128-8-8-1.4e-5_adam
[08:42:06] WARNING  The following values were not passed to `accelerate launch` and had defaults used         launch.py:895
                    instead:
                            `--num_processes` was set to a value of `0`
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/trl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/opt/conda/envs/trl/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /opt/conda/envs/trl didnot contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/opt/conda/envs/trl/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /opt/conda/envs/trl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
Found cached dataset parquet (/root/.cache/huggingface/datasets/lvwerra___parquet/lvwerra--stack-exchange-paired-e5ccc5f74f1da5b7/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
Found cached dataset parquet (/root/.cache/huggingface/datasets/lvwerra___parquet/lvwerra--stack-exchange-paired-e5ccc5f74f1da5b7/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
Loading cached processed dataset at /root/.cache/huggingface/datasets/lvwerra___parquet/lvwerra--stack-exchange-paired-e5ccc5f74f1da5b7/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-699bd47ea7fff798_*_of_00024.arrow
Loading cached processed dataset at /root/.cache/huggingface/datasets/lvwerra___parquet/lvwerra--stack-exchange-paired-e5ccc5f74f1da5b7/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-8ba7d03bf81aa83c.arrow
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loadingin mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.59s/it]

Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loadingin mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.91s/it]
Some weights of the model checkpoint at /xxx/merged7breward were not used when initializing LlamaForSequenceClassification: ['lm_head.weight']
- This IS expected if you are initializing LlamaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loadingin mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.74s/it]
The model 'LlamaForCausalLM' is not supported for sentiment-analysis. Supported models are 
['AlbertForSequenceClassification', 'BartForSequenceClassification', 'BertForSequenceClassification', 
'BigBirdForSequenceClassification', 'BigBirdPegasusForSequenceClassification', 'BloomForSequenceClassification', 
'CamembertForSequenceClassification', 'CanineForSequenceClassification', 'ConvBertForSequenceClassification', 
'CTRLForSequenceClassification', 'Data2VecTextForSequenceClassification', 'DebertaForSequenceClassification', 
'DebertaV2ForSequenceClassification', 'DistilBertForSequenceClassification', 'ElectraForSequenceClassification', 
'ErnieForSequenceClassification', 'ErnieMForSequenceClassification', 'EsmForSequenceClassification', 
'FlaubertForSequenceClassification', 'FNetForSequenceClassification', 'FunnelForSequenceClassification', 
'GPT2ForSequenceClassification', 'GPT2ForSequenceClassification', 'GPTBigCodeForSequenceClassification', 
'GPTNeoForSequenceClassification', 'GPTNeoXForSequenceClassification', 'GPTJForSequenceClassification', 
'IBertForSequenceClassification', 'LayoutLMForSequenceClassification', 'LayoutLMv2ForSequenceClassification', 
'LayoutLMv3ForSequenceClassification', 'LEDForSequenceClassification', 'LiltForSequenceClassification', 
'LlamaForSequenceClassification', 'LongformerForSequenceClassification', 'LukeForSequenceClassification', 
'MarkupLMForSequenceClassification', 'MBartForSequenceClassification', 'MegaForSequenceClassification', 
'MegatronBertForSequenceClassification', 'MobileBertForSequenceClassification', 'MPNetForSequenceClassification', 
'MvpForSequenceClassification', 'NezhaForSequenceClassification', 'NystromformerForSequenceClassification', 
'OpenAIGPTForSequenceClassification', 'OPTForSequenceClassification', 'PerceiverForSequenceClassification', 
'PLBartForSequenceClassification', 'QDQBertForSequenceClassification', 'ReformerForSequenceClassification', 
'RemBertForSequenceClassification', 'RobertaForSequenceClassification', 'RobertaPreLayerNormForSequenceClassification', 
'RoCBertForSequenceClassification', 'RoFormerForSequenceClassification', 'SqueezeBertForSequenceClassification', 
'TapasForSequenceClassification', 'TransfoXLForSequenceClassification', 'XLMForSequenceClassification', 
'XLMRobertaForSequenceClassification', 'XLMRobertaXLForSequenceClassification', 'XLNetForSequenceClassification', 
'XmodForSequenceClassification', 'YosoForSequenceClassification'].

0it [00:00, ?it/s]/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py:104: UserWarning: `return_all_scores` is now deprecated,  if want a similar funcionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(
0it [00:18, ?it/s]
Traceback (most recent call last):
  File "/mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/rl_training.py", line 253, in <module>
    pipe_outputs = sentiment_pipe(texts, **sent_kwargs)
  File "/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py", line 155, in __call__
    result = super().__call__(*args, **kwargs)
  File "/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1090, in __call__
    outputs = list(final_iterator)
  File "/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py", line 214, in postprocess
    dict_scores = [
  File "/opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py", line 215, in <listcomp>
    {"label": self.model.config.id2label[i], "score": score.item()} for i, score in enumerate(scores)
ValueError: can only convert an array of size 1 to a Python scalar
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/rl_training.py:253 in         │
│ <module>                                                                                         │
│                                                                                                  │
│   250 │                                                                                          │
│   251 │   # Compute sentiment score                                                              │
│   252 │   texts = [q + r for q, r in zip(batch["query"], batch["response"])]                     │
│ ❱ 253 │   pipe_outputs = sentiment_pipe(texts, **sent_kwargs)                                    │
│   254 │   rewards = [torch.tensor(output[0]["score"] - script_args.reward_baseline) for output   │
│   255 │                                                                                          │
│   256 │   # Run PPO step                                                                         │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py:1 │
│ 55 in __call__                                                                                   │
│                                                                                                  │
│   152 │   │   │                                                                                  │
│   153 │   │   │   If `top_k` is used, one such dictionary is returned per label.                 │
│   154 │   │   """                                                                                │
│ ❱ 155 │   │   result = super().__call__(*args, **kwargs)                                         │
│   156 │   │   # TODO try and retrieve it in a nicer way from _sanitize_parameters.               │
│   157 │   │   _legacy = "top_k" not in kwargs                                                    │
│   158 │   │   if isinstance(args[0], str) and _legacy:                                           │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/base.py:1090 in __call__ │
│                                                                                                  │
│   1087 │   │   │   │   final_iterator = self.get_iterator(                                       │
│   1088 │   │   │   │   │   inputs, num_workers, batch_size, preprocess_params, forward_params,   │
│   1089 │   │   │   │   )                                                                         │
│ ❱ 1090 │   │   │   │   outputs = list(final_iterator)                                            │
│   1091 │   │   │   │   return outputs                                                            │
│   1092 │   │   │   else:                                                                         │
│   1093 │   │   │   │   return self.run_multi(inputs, preprocess_params, forward_params, postpro  │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py:125 in       │
│ __next__                                                                                         │
│                                                                                                  │
│   122 │   │                                                                                      │
│   123 │   │   # We're out of items within a batch                                                │
│   124 │   │   item = next(self.iterator)                                                         │
│ ❱ 125 │   │   processed = self.infer(item, **self.params)                                        │
│   126 │   │   # We now have a batch of "inferred things".                                        │
│   127 │   │   if self.loader_batch_size is not None:                                             │
│   128 │   │   │   # Try to infer the size of the batch                                           │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py:2 │
│ 14 in postprocess                                                                                │
│                                                                                                  │
│   211 │   │   if top_k == 1 and _legacy:                                                         │
│   212 │   │   │   return {"label": self.model.config.id2label[scores.argmax().item()], "score"   │
│   213 │   │                                                                                      │
│ ❱ 214 │   │   dict_scores = [                                                                    │
│   215 │   │   │   {"label": self.model.config.id2label[i], "score": score.item()} for i, score   │
│   216 │   │   ]                                                                                  │
│   217 │   │   if not _legacy:                                                                    │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text_classification.py:2 │
│ 15 in <listcomp>                                                                                 │
│                                                                                                  │
│   212 │   │   │   return {"label": self.model.config.id2label[scores.argmax().item()], "score"   │
│   213 │   │                                                                                      │
│   214 │   │   dict_scores = [                                                                    │
│ ❱ 215 │   │   │   {"label": self.model.config.id2label[i], "score": score.item()} for i, score   │
│   216 │   │   ]                                                                                  │
│   217 │   │   if not _legacy:                                                                    │
│   218 │   │   │   dict_scores.sort(key=lambda x: x["score"], reverse=True)                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: can only convert an array of size 1 to a Python scalar
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run still-disco-12 at: https://wandb.ai/pegasus-wenjia/trl/runs/nlvfkkmr
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230428_084237-nlvfkkmr/logs
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/conda/envs/trl/bin/accelerate:8 in <module>                                                 │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py:45 in     │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/accelerate/commands/launch.py:923 in            │
│ launch_command                                                                                   │
│                                                                                                  │
│   920 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   921 │   │   sagemaker_launcher(defaults, args)                                                 │
│   922 │   else:                                                                                  │
│ ❱ 923 │   │   simple_launcher(args)                                                              │
│   924                                                                                            │
│   925                                                                                            │
│   926 def main():                                                                                │
│                                                                                                  │
│ /opt/conda/envs/trl/lib/python3.10/site-packages/accelerate/commands/launch.py:579 in            │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   576 │   process.wait()                                                                         │
│   577 │   if process.returncode != 0:                                                            │
│   578 │   │   if not args.quiet:                                                                 │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   580 │   │   else:                                                                              │
│   581 │   │   │   sys.exit(1)                                                                    │
│   582                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/opt/conda/envs/trl/bin/python3.10', 'rl_training.py', '--log_with=wandb',
'--model_name=/mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/merged7bsft',
'--reward_model_name=/mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/merged7breward',
'--adafactor=False', '--tokenizer_name', 'huggingface/llama-7b', '--save_freq=100', '--output_max_length=128',
'--batch_size=4', '--gradient_accumulation_steps=8', '--batched_gen=True', '--ppo_epochs=4', '--seed=0',
'--learning_rate=1.4e-5', '--early_stopping=True', '--output_dir=llama-se-rl-finetune-128-8-8-1.4e-5_adam']' returned
non-zero exit status 1.
```

**Comment by younesbelkada** [comment]
Hello @vpegasus 
Thanks for the ping! 
It seems that you are using an old version of `transformers` that does not support `LlamaForSequenceClassification`.
I would suggest to install `transformers` from source to be on the safe zone: https://github.com/huggingface/transformers/blob/a0e733283930bdb9ae2b1afdc53ec5f2daefb033/src/transformers/models/llama/modeling_llama.py#L781 
Can you try to uninstall `transformers` and re-install it with:
```bash
pip install git+https://github.com/huggingface/transformers.git
```

**Comment by vpegasus** [comment]
> Hello @vpegasus Thanks for the ping! It seems that you are using an old version of `transformers` that does not support `LlamaForSequenceClassification`. I would suggest to install `transformers` from source to be on the safe zone: https://github.com/huggingface/transformers/blob/a0e733283930bdb9ae2b1afdc53ec5f2daefb033/src/transformers/models/llama/modeling_llama.py#L781 Can you try to uninstall `transformers` and re-install it with:
> 
> ```shell
> pip install git+https://github.com/huggingface/transformers.git
> ```

Hi, @vpegasus  thanks for your kindly reply! it worked! 
However,  while the training is running, I got the warning message: `KL divergence is starting to become negative: -0.20 - this might be a precursor for failed training. sometimes this happens because the generation kwargs are not correctly set. Please make sure that the generation kwargs are set correctly, or review your training hyperparameters.`

this is the command I used:
```bash
accelerate launch rl_training.py \
--log_with=wandb --model_name=/mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/merged7bsft \
--reward_model_name=/mnt/disks/data-1/marvin/projects/trl/examples/stack_llama/scripts/merged7breward \
--adafactor=False \
--tokenizer_name huggingface/llama-7b \
--save_freq=100 \
--output_max_length=128 --batch_size=4 --gradient_accumulation_steps=16 \
--batched_gen=True --ppo_epochs=4 --seed=0 --learning_rate=1.4e-5 \
--early_stopping=True --output_dir=llama-se-rl-finetune-128-8-8-1.4e-5_adam
```

What I should do to avoid negative KL divergence?
Thanks.

**Comment by kungfu-eric** [comment]
Probably needs a new issue, but it's discussed on their post: https://huggingface.co/blog/stackllama

> Clearly, when a token is sampled from the policy which has a lower probability than the SFT model, this will lead to a negative KL penalty, but on average it will be positive otherwise you wouldn't be properly sampling from the policy. However, some generation strategies can force some tokens to be generated or some tokens can suppressed. For example when generating in batches finished sequences are padded and when setting a minimum length the EOS token is suppressed. The model can assign very high or low probabilities to those tokens which leads to negative KL. As the PPO algorithm optimizes for reward, it will chase after these negative penalties, leading to instabilities.

Maybe don't set a minimum length or generate in batch size 1 to avoid excessive padding.

**Comment by vpegasus** [comment]
ok, thanks, I'll try latter
