### ISSUE TITLE
`gpt-neox-20b_peft/merge_peft_adapter.py` script fails

### ISSUE THREAD

**Issue by ckinateder** [lvwerra/trl#432]
I've been trying to run the script `examples/sentiment/scripts/gpt-neox-20b_peft/merge_peft_adapter.py`. It fails with this full traceback:

```python
$ accelerate launch scripts/gpt-neox-20b_peft/merge_peft_adapter.py 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/calkin0j/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
CUDA SETUP: CUDA runtime path found: /usr/lib/x86_64-linux-gnu/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/calkin0j/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
Traceback (most recent call last):
  File "/home/calkin0j/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 278, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/calkin0j/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute '_get_submodules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/calkin0j/trl/examples/sentiment/scripts/gpt-neox-20b_peft/merge_peft_adapter.py", line 39, in <module>
    parent, target, target_name = model.base_model._get_submodules(key)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/peft/tuners/lora.py", line 280, in __getattr__
    return getattr(self.model, name)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTNeoForCausalLM' object has no attribute '_get_submodules'. Did you mean: 'get_submodule'?
Traceback (most recent call last):
  File "/home/calkin0j/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.10', 'scripts/gpt-neox-20b_peft/merge_peft_adapter.py']' returned non-zero exit status 1.
```

Any fix?

**Comment by younesbelkada** [comment]
Hi @ckinateder 
Thanks for the issue!
I think that you are using an outdated version of the merging script. Please pull the latest version of the merging script: https://github.com/lvwerra/trl/blob/main/examples/stack_llama/scripts/merge_peft_adapter.py and make sure you are using at least `peft==0.3.0` and re-run the script. 
Thanks!

**Comment by ckinateder** [comment]
Thanks for the quick response @younesbelkada. Should the merge script for the `gpt-neox-20b_peft` example be the same as the one in the `stack_llama` example?

**Comment by younesbelkada** [comment]
Hi @ckinateder 
No worries! I believe that you just need to provide the correct paths to the respective adapter and base models
`--adapter_model_name` and `--base_model_name` and it should work properly!

**Comment by ckinateder** [comment]
@younesbelkada, that's what I was thinking too. I tried it with

```bash
accelerate launch scripts/gpt-neox-20b_peft/merge_peft_adapter.py --adapter_model_name facebook/opt-125m --base_model_name edbeeching/gpt-neo-125M-imdb-lora
```

This gave me the traceback:

```python
$ accelerate launch scripts/gpt-neox-20b_peft/merge_peft_adapter.py --adapter_model_name facebook/opt-125m --base_model_name edbeeching/gpt-neo-125M-imdb-lora

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/calkin0j/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
CUDA SETUP: CUDA runtime path found: /usr/lib/x86_64-linux-gnu/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/calkin0j/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
Traceback (most recent call last):
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/calkin0j/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/opt-125m/resolve/main/adapter_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/calkin0j/.local/lib/python3.10/site-packages/peft/utils/config.py", line 106, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME, subfolder=subfolder)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6488a30c-36e2b50d5c4e5c4b12e31a8b)

Entry Not Found for url: https://huggingface.co/facebook/opt-125m/resolve/main/adapter_config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/calkin0j/trl/examples/sentiment/scripts/gpt-neox-20b_peft/merge_peft_adapter.py", line 26, in <module>
    peft_config = PeftConfig.from_pretrained(script_args.adapter_model_name)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/peft/utils/config.py", line 108, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at 'facebook/opt-125m'
Traceback (most recent call last):
  File "/home/calkin0j/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/home/calkin0j/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.10', 'scripts/gpt-neox-20b_peft/merge_peft_adapter.py', '--adapter_model_name', 'facebook/opt-125m', '--base_model_name', 'edbeeching/gpt-neo-125M-imdb-lora']' returned non-zero exit status 1.
```

Any ideas on how to fix this? I'm following the procedure in [this huggingface blog post](https://huggingface.co/blog/trl-peft). According to the 3 scripts in the `gpt-neox-20b_peft` directory, I believe the base model name should be `edbeeching/gpt-neo-125M-imdb-lora` and the adapter model name should be `facebook/opt-125m`.

**Comment by lvwerra** [comment]
Hi @ckinateder,  `--adapter_model_name` should point to an adapter for `--base_model_name `. However,`facebook/opt-125m` is a base model and `edbeeching/gpt-neo-125M-imdb-lora` is an adapter for `gpt-neo-125m` rather than `opt-125m`.

**Comment by o-github-o** [comment]
the gpt-neox-20b_peft file has been removed?

**Comment by younesbelkada** [comment]
Hi @o-github-o 
Yes it has been removed as now you just need to call a one-liner to merge adapter weights into the base model. Check out [this specific section](https://huggingface.co/docs/peft/conceptual_guides/lora#merge-lora-weights-into-the-base-model) on PEFT documentation to learn more about it.

```python
... 
model = model.merge_and_unload()
```
