### ISSUE TITLE
[bug] Size mismatch for Peft PromptTuning

### ISSUE THREAD

**Issue by ain-soph** [lvwerra/trl#490]
### Description

PromptTuning in Peft insert the tuned-prompt at the beginning of inputs,
https://github.com/huggingface/peft/blob/032fff92fb74b737a2934e91a08d82142fb79dc3/src/peft/peft_model.py#L1150-L1157

making the model output shape no longer `[batch_size, dim]` but `[batch_size, num_virtual_tokens + dim]`.

This leads to a size-mismatch problem during
https://github.com/lvwerra/trl/blob/aa9770c6bd08a5874c70eda0423a88f457b3eea9/trl/trainer/ppo_trainer.py#L1016-L1017

where `values` shape is `[batch_size, num_virtual_tokens + dim]` (because it is Peft model outputs),  
while `rewards` and `mask` shape are still `[batch_size, dim]` (because they don't call Peft model)

For example, here is a sample data shape record for all variables:
```
queries [torch.Size([79])]
responses [torch.Size([179])]
logprobs torch.Size([1, 257])
values torch.Size([1, 307])
rewards torch.Size([1, 257])
masks torch.Size([1, 257])
input_ids torch.Size([1, 258])
attention_mask torch.Size([1, 258])
```

### Workaround

Add following snippet
```python3
            if (offset := values.size(1) - attention_mask.size(1)):
                values = values[:, offset:]
            if (offset := logits.size(1) - attention_mask.size(1)):
                logits = logits[:, offset:]
```
to 
https://github.com/lvwerra/trl/blob/aa9770c6bd08a5874c70eda0423a88f457b3eea9/trl/trainer/ppo_trainer.py#L870

**Comment by ain-soph** [comment]
A snippet to reproduce:
#### snippet
```python3
from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer
import transformers
import peft
import torch

reward_model_path = 'facebook/roberta-hate-speech-dynabench-r4-target'
reward_tokenizer = transformers.AutoTokenizer.from_pretrained(
    reward_model_path,
    torch_dtype='auto', device_map='auto', low_cpu_mem_usage=True,
)
reward_model = transformers.AutoModelForSequenceClassification.from_pretrained(
    reward_model_path,
    torch_dtype='auto', low_cpu_mem_usage=True, device_map='auto',
    quantization_config=transformers.BitsAndBytesConfig(
        load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        llm_int8_enable_fp32_cpu_offload=True
    ),
)


def get_reward(prompt: str):
    reward_inputs = reward_tokenizer(prompt, return_tensors="pt")
    reward_logits = reward_model(reward_inputs.input_ids.cuda()).logits
    return torch.softmax(reward_logits, dim=-1).flatten()


model_path = 'lmsys/vicuna-7b-v1.3'
tokenizer = transformers.LlamaTokenizer.from_pretrained(
    model_path, torch_dtype='auto', device_map='auto', low_cpu_mem_usage=True,
)
peft_config = peft.PromptTuningConfig(
    task_type=peft.TaskType.CAUSAL_LM,
    num_virtual_tokens=10,
    tokenizer_name_or_path=model_path,
    inference_mode=False,
)
model = AutoModelForCausalLMWithValueHead.from_pretrained(
    model_path, peft_config=peft_config, torch_dtype='auto', low_cpu_mem_usage=True,
    device_map='auto',
    quantization_config=transformers.BitsAndBytesConfig(
        load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        llm_int8_enable_fp32_cpu_offload=True
    ),
)
model.pretrained_model.prompt_encoder.to(model.pretrained_model.device)


ppo_config = PPOConfig(
    learning_rate=5e-4,
    batch_size=1,
    mini_batch_size=1,
    gradient_accumulation_steps=4,
    target_kl=1.0,
    ppo_epochs=6,
    init_kl_coef=1000.0,
    adap_kl_ctrl=True,

    early_stopping=False,
    seed=0,
    log_with=None,  # 'wandb'
    optimize_cuda_cache=True,
)

ppo_trainer = PPOTrainer(
    ppo_config,
    model,
    tokenizer=tokenizer
)

prompt = 'Who is the president of the United States?'
inputs = tokenizer(prompt, return_tensors="pt")
generation_config = transformers.GenerationConfig(max_new_tokens=100)
query = inputs.input_ids.cuda()

score = get_reward(prompt)[1:]

response = model.generate(
    input_ids=query, generation_config=generation_config,
    attention_mask=inputs.attention_mask.to(device=query.device),
)
response_str = tokenizer.batch_decode(
    response[:, query.size(1):],
)[0].split('\n')[0]

score = get_reward(response_str)[1:]

ppo_trainer.step(
    queries=list(query.unbind()),
    responses=list(response.unbind()),
    scores=list(score.unbind()),
)

```

#### Log
```
/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py:232: UserWarning: No dataset is provided. Make sure to set config.batch_size to the correct value before training.
  warnings.warn(
Traceback (most recent call last):
  File "/local/home/user/workspace/test_bug.py", line 89, in <module>
    ppo_trainer.step(
  File "/home/user/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 675, in step
    train_stats = self.train_minibatch(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 938, in train_minibatch
    loss_p, loss_v, train_stats = self.loss(old_logprobs, values, rewards, logits, vpreds, logprobs, mask)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/trl/trainer/ppo_trainer.py", line 1016, in loss
    values = values * mask
             ~~~~~~~^~~~~~
RuntimeError: The size of tensor a (129) must match the size of tensor b (119) at non-singleton dimension 1
```

**Comment by younesbelkada** [comment]
Hi @ain-soph 
Thanks for reporting, just made: https://github.com/lvwerra/trl/pull/500 that should hopefully resolve your issue

**Comment by younesbelkada** [comment]
Hi @ain-soph 
Again thanks for reporting, after digging a bit, it might be tricky to support PPO with prompt tuning, check out this comment for referece: https://github.com/lvwerra/trl/pull/500#issuecomment-1623623554 and let us know if anything is unclear

**Comment by ain-soph** [comment]
@younesbelkada That makes sense. Thanks for help!
