### ISSUE TITLE
PPO Trainer Fails with Accelerate

### ISSUE THREAD

**Issue by Ravisutha** [lvwerra/trl#625]
Setup Info:
Multi-gpu single node

Here's the pseudo code that mimics my setup:

```python
# Load model in peft
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM,
)

model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(
    config.model_name,
    load_in_8bit=True,
    device_map={"": current_device},
    peft_config=lora_config,
)

# Prep PPO Trainer
config = PPOConfig(
    model_name=script_args.model_name,
    learning_rate=script_args.learning_rate,
    batch_size=script_args.batch_size,
    mini_batch_size=script_args.mini_batch_size,
    gradient_accumulation_steps=script_args.gradient_accumulation_steps,
    optimize_cuda_cache=True,
    early_stopping=script_args.early_stopping,
    target_kl=script_args.target_kl,
    ppo_epochs=script_args.ppo_epochs,
    seed=script_args.seed,
    init_kl_coef=script_args.init_kl_coef,
    adap_kl_ctrl=script_args.adap_kl_ctrl,
    accelerator_kwargs={"logging_dir": script_args.logging_dir},
    tracker_project_name="some-name", 
    log_with="tensorboard"
)

ppo_trainer = PPOTrainer(
    config,
    model,
    tokenizer=tokenizer,
    dataset=train_dataset,
    optimizer=optimizer,
)

# Inside the training loop:
train_stats = ppo_trainer.step(
    [query_tokens.to(torch.int32)],
    [response_tensor[0]],
    [reward[0]]
)
```

With #546 (v0.5.0), the following error is seen while executing ppo_trainer.step():

```
Traceback (most recent call last):  File "/opt/ml/code/train.py", line 216, in <module>
--
stats, rewards = train_step(model, similarity_model, ppo_trainer, tokenizer, batch)  
File "/opt/ml/code/train.py", line 67, in train_step
train_stats = ppo_trainer.step(  
File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)  
File "/opt/conda/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py", line 724, in step
logprobs, logits, vpreds, _ = self.batched_forward_pass(  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)  File "/opt/conda/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py", line 952, in batched_forward_pass
torch.cat(all_logprobs),
RuntimeError
: torch.cat(): expected a non-empty list of Tensors
```

But with `v0.4.7`, it works fine with the same setup and code.

NOTE: I am unable to reproduce this on CPU with `v0.5.0`. So, I am guessing that it might be related to integration with `accelerate`?

**Comment by lvwerra** [comment]
This seems to the same issue as reported in #614. Could you try the suggestion there? And let's use the other issue to track progress.
