### ISSUE TITLE
IndexError: dimension specified as -2 but tensor has no dimensions

### ISSUE THREAD

**Issue by thak123** [lvwerra/trl#9]
I am trying to run /04-gpt2-sentiment-ppo-training.ipynb but I encounter this error. Any fix for this ?
I am using the transformers 3.4.0

0%|          | 0/200 [00:00<?, ?it/s]/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_gpt2.py:532: FutureWarning: The `past` argument is deprecated and will be removed in a future version, use `past_key_values` instead.
  FutureWarning,
  0%|          | 0/200 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/media/gaurish/angela/projects/rl-sentiment/main.py", line 148, in <module>
    attention_masks[i*fbs:(i+1)*fbs])[0][:, 1].detach()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_gpt2.py", line 1032, in forward
    return_dict=return_dict,
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/transformers/modeling_gpt2.py", line 565, in forward
    past_length = past_key_values[0][0].size(-2)
IndexError: dimension specified as -2 but tensor has no dimensions

**Comment by lvwerra** [comment]
Hi @thak123! Thanks for the report. Last time I tested the library was with `transformers==2.6.0`. Can you try again with this version?

**Comment by thak123** [comment]
Sure

**Comment by lvwerra** [comment]
Any luck?

**Comment by thak123** [comment]
Yes.Sorry didn't reply earlier but it worked fine. Thanks
